### ISSUE TITLE
file export should warn if user tries to include all of the file repository files

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/kiosk#1363]
The file export only exports files if the file picking rules allow for it. However, the file repository can be tens of gigabytes worth of image and it would not be fun to download that ZIP file (I am not even sure it would work).
So two warnings might help:

### tasks
This is what we do as a quick solution if files are to be included:
- [x] STOP the file export if there are NO file picking rules or the file picking rules lead to no results
- [x] STOP the file export after having exceeded a certain limit of image sizes.

see also #1366 as another possible solution to the file size overkill. But that's for later.,

**Comment by urapadmin** [comment]
This is what we do as a quick solution:
STOP the file export after having exceeded a certain limit of image sizes.

**Comment by urapadmin** [comment]
Three is a new configuration **max_export_repo_mbytes** for the file export:
```yaml
fileexportworkstation:
  max_export_repo_mbytes: 20
```
It sets the limit in Megabytes that the repository files included in the export should not exceed.

**Comment by urapadmin** [comment]
### @test v0.15
- [ ] if there are no file picking rules defined the export should stop after the fork with an error
- [ ] if the total size of the picked repository files exceeds 100MBytes (the default) the export should stop with an error

**Comment by luizaogs** [comment]
Hm no, it didn't. I haven't defined file picking rules yet and it exported anyway (I did fork again).

**Comment by luizaogs** [comment]
Ok well this is weird. Now that I HAVE set file picking rules I got the error:

<img width="1512" alt="Screen Shot 2022-02-13 at 6 00 19 PM" src="https://user-images.githubusercontent.com/67970402/153781241-50faa617-540d-4144-bfed-26d0e7705dd3.png">

**Comment by urapadmin** [comment]
Hmpf

**Comment by urapadmin** [comment]
ha. You sent me on a wild goose chase 🦢🦢🦢 (no geese here, swans must do). 
"record_type" in "LA" is not what you wanted, I suppose. You wanted "context" in "LA", right?

**Comment by luizaogs** [comment]
Oh dear god.  Yes. I told you I was losing my mind.

**Comment by luizaogs** [comment]
Wait, but the error still only worked when I had the rules so I guess something is still wrong?

**Comment by urapadmin** [comment]
the what, the who?

**Comment by urapadmin** [comment]
> Hm no, it didn't. I haven't defined file picking rules yet and it exported anyway (I did fork again).

you mean this one? Hm. I tried that in my development environment and it worked.

**Comment by urapadmin** [comment]
hmpf hmpf.

**Comment by luizaogs** [comment]
ARGH I swear it hadn't worked before but it did now. You should just ignore me from now on!

**Comment by urapadmin** [comment]
no way

**Comment by urapadmin** [comment]
is it possible that the "include files" checkbox wasn't checked? In that case the error would not occur.

**Comment by urapadmin** [comment]
(did it ever occur to me that I might temper with the code while you are testing to make you go insane?)

**Comment by luizaogs** [comment]
I'm pretty sure I checked it because I remember choosing the descriptive names option so I could test that ticket as well, so....

**Comment by urapadmin** [comment]
👿

**Comment by luizaogs** [comment]
That would be evil! Did you????

**Comment by luizaogs** [comment]
And here I was feeling bad for sending you on a wild swan chase.

**Comment by urapadmin** [comment]
I'd say we just shrug it. Don't know what could have happened (I could search the logs but ... 🍷 )

**Comment by luizaogs** [comment]
Just to make sure, is this the error that should appear if the zip would be too big?

<img width="1512" alt="Screen Shot 2022-02-13 at 7 31 44 PM" src="https://user-images.githubusercontent.com/67970402/153785578-2965ee2c-3dca-4f3b-9a54-e67c50860697.png">

**Comment by urapadmin** [comment]
not at all.

**Comment by luizaogs** [comment]
Ha. Well. It did.

<img width="1477" alt="Screen Shot 2022-02-13 at 7 34 13 PM" src="https://user-images.githubusercontent.com/67970402/153785693-31722059-ce6e-4efd-b52f-413ad7427a74.png">

**Comment by urapadmin** [comment]
ja, that is a fork issue that would happen to normal workstations as well. It seems Meghan's Canon Raw files didn't go down well :).
We'll make that its own issue.

**Comment by urapadmin** [comment]
I'll give you a limit of 10MB so that you have an easier time to test the second one ...

**Comment by urapadmin** [comment]
Limit in place.

**Comment by luizaogs** [comment]
Worked! Hallelujah. Sorry for the madness.
